### ISSUE TITLE
Run Simpletests in travisCI

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/i18n#28]
A comment in a [previous Issue](https://github.com/backdrop-contrib/i18n/issues/22#issuecomment-619377469):

> we should get these (Simpletests) to run in travisCI too;

That would be really cool.

@serundeputy I have no travisCI expertise at all, so I can't be much help here.

----
PR: https://github.com/backdrop-contrib/i18n/pull/31

**Comment by serundeputy** [comment]
@indigoxela ready for review: https://github.com/backdrop-contrib/i18n/pull/31

Run simpletests in CI via lando.

**Comment by serundeputy** [comment]
we should consider adding a testing badge to the README when/if this is merged

```md
[![Build Status](https://travis-ci.org/backdrop-contrib/i18n.svg?branch=1.x)](https://travis-ci.org/backdrop-contrib/i18n)
```

**Comment by indigoxela** [comment]
> consider adding a testing badge to the README

Sure, but I still have questions regarding the travis test run.

Why is there a PHP Stack trace?

Why Xenial?

Why all those useless updates (docker, postgres..) of stuff we don't even need? (Or do we need it?)

Why lando? Isn't that overhead?

**Comment by serundeputy** [comment]
* ~~I don't know anything about a PHP stack trace~~
  * ahh; i see the PHP stack trace is in the `phpcs` run output on travis; i think that is php 7.3 complaining about how our old `phpcs` handles things, but it does not hurt the code linting; we could try building php 7.2, but it doesn't bother me

* Xenial has the version of docker that we want
we are doing an `apt update` to make sure we `apt install *` latest versions of `*`, but i'm not aware of or seeing updates to postgres (unless they happen in the automatic part of travis which we have no control over)

* lando in CI is pattern we use a lot at my agency, so i'm letting lando/docker set up the tech stack instead of mucking around w/ travis config; so lando matches production, lando runs in CI then deploy to production
  * lando is also how i'm running these tests locally, so know my local runs and CI are the same

**Comment by indigoxela** [comment]
> I don't know anything about a PHP stack trace

I mean that one:

![screenshot-travis](https://user-images.githubusercontent.com/842066/80865186-f0fff000-8c87-11ea-840c-d9e8173bfadf.png)

Re lando, composer, xenial... give me some time to think it over. :wink:

**Comment by indigoxela** [comment]
So... I thought it over and gave travisCI a try.

To be honest, I'd actually prefer the way with less overhead (hence shorter time until testbox is up and running).

https://travis-ci.org/github/backdrop-contrib/i18n/builds/683796501

And without exception or traceback.

It turned out, I don't even need drush.
