### ISSUE TITLE
Deleting localized vocabulary gives error

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#70]
Deleting a localized vocabulary with terms in it gives the following error: 

> Error: Call to a member function get_translations() on int in i18n_taxonomy_taxonomy_term_delete() (line 632 of /app/modules/i18n/i18n_taxonomy/i18n_taxonomy.module). 

When I reload the page, the terms are gone and I can now successfully delete the vocabulary in a second attempt.

**Comment by indigoxela** [comment]
Seems like a bug, but I struggle to reproduce.

My approaches:

- Create a vocab, set to "localized", translate
- Add term, translate
- Delete vocab
- No error

Second approach:

- Add vocab, set to "localized" and translate
- Add term, but do not translate
- Delete vocab
- No error

Third approach:

- Add vocab, set to "localized", do not translate
- Add term, do not translate
- Delete vocab
- No error

@laryn which step might I be missing?

**Comment by indigoxela** [comment]
Now I found a way to reproduce - switching the i18n_mode can cause trouble.

My steps:

- Create a vocab, set it to "translate"
- Add a term and translate
- Switch vocab to "localize"
- Delete the vocab
- Error: Call to a member function get_translations() on int - it is `0`

Should be fixed in 2a063171
